SET SQL_MODE = " NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

    	CREATE TABLE 'contact' (
		`id` INT (100) NOT NULL,
		`Name` VARCHAR(50) NOT NULL,
		`Email` VARCHAR(50) NOT NULL UNIQUE,
		`Number` VARCHAR(50) NULL,
		`Date` VARCHAR(50) NULL
		)ENGINE = INNODB DEFAULT CHARSET = utf8mb4;

		ALTER TABLE `contact`
		ADD PRIMARY KEY (`id`);

		ALTER TABLE `contact`
		 MODIFY `id` INT(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
		 COMMIT;
		